idc changed a lot of files

diff --git a/.local/bin/source/src_add_path b/.local/bin/source/src_add_path
--- a/.local/bin/source/src_add_path
+++ b/.local/bin/source/src_add_path
@@ -1,3 +1,15 @@
-export PATH="$1:$PATH"
+[ -z "$1" ] && {
+    echo "Missing path parameter!" >&2
+    return 1
+}
+
+full_path="$(readlink -e "$1")"
+
+[ ! -d "$full_path" ] && {
+    echo "Path doesn't exist!" >&2
+    return 1
+}
+
+export PATH="$full_path:$PATH"
 
 # vim: ft=sh
